# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

version: "3"
services:
  upbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upbot
    restart: always
    volumes:
      - ./configs:/app/configs
    image: upbot:latest
    ports:
      - "9120:9120"